apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-nginx
  name: nginx-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  type: NodePort
  selector:
    app: deployment-nginx
status:
  loadBalancer: {}
